[package]
name = "ember-core"
version = "0.1.0"
edition = "2024"

[dependencies]
ed25519-dalek = "2"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
bincode = "1.3"
sha2 = "0.10"
chacha20poly1305 = "0.10.1"
serde_json = "1.0.149"
hex = "0.4.3"
ratatui = "0.30.0"
crossterm = "0.29.0"

